#!/bin/bash

echo "Uploading MESSAGE THREADS and CHAT MESSAGES data..."

echo ""
echo "Uploading MESSAGE THREADS..."
npx convex run insertData:insertData '{"table": "messageThreads", "data": [{"threadId":"MSG-001","customerName":"Goldwinter Homantin","lastMessage":"Ill send my measurements tonight so we stay on track.","timestamp":"下午 4:05","unread":true,"avatar":"https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?q=80&w=120&auto=format&fit=crop","productId":12},{"threadId":"MSG-002","customerName":"Natalie Brooks","lastMessage":"Ill confirm the flight dates and book the fitting slot.","timestamp":"上午 10:40","unread":true,"avatar":"https://images.unsplash.com/photo-1524504388940-b1c1722653e1?q=80&w=120&auto=format&fit=crop","productId":13},{"threadId":"MSG-003","customerName":"設計師 Ada","lastMessage":"今晚前會畫個草圖俾你。","timestamp":"昨天","unread":false,"avatar":"https://picsum.photos/seed/msg3/100/100","productId":14}]}'

echo ""
echo "Uploading CHAT MESSAGES (first batch)..."
npx convex run insertData:insertData '{"table": "chatMessages", "data": [{"messageId":"MSG-001-1","threadId":"MSG-001","sender":"customer","originalText":"Hello Master Wong, I just generated this blue dragon cheongsam concept. Could we explore making a real piece together?\\n\\nIve included the pattern draft for reference as well.\\n\\n<image src=\\\"/images/presets/dragon.jpeg\\\" alt=\\\"Blue dragon concept\\\" />\\n<image src=\\\"/images/presets/dragon_draft.png\\\" alt=\\\"Pattern draft\\\" />","translatedText":"王師傅您好，我啱啱生成咗一個藍龍長衫概念。可唔可以幫我做成實物？\\n\\n我同時附上布料草圖方便參考。","language":"en","timestamp":"下午 3:12"},{"messageId":"MSG-001-2","threadId":"MSG-001","sender":"artisan","originalText":"多謝你分享藍龍嘅概念圖同草稿。我會安排龍紋盤金繡穿過前幅，袖口再加少少雲紋。先落訂二千港幣，我會出線稿同布料提案俾你確認。","translatedText":"Thanks for sharing the concept and draft. I can sweep the dragon embroidery across the front panel and add soft cloud motifs on the cuffs. A HK$2,000 deposit lets me prepare the line art and fabric proposals for your approval.","language":"zh","timestamp":"下午 3:25"},{"messageId":"MSG-001-3","threadId":"MSG-001","sender":"customer","originalText":"<system class=\\\"payment-alert\\\">Craftscape Pay ✅\\nTransaction ID: CSP-9285\\nDeposit HK$2,000 received via platform.</system>","language":"en","timestamp":"下午 3:42"},{"messageId":"MSG-001-4","threadId":"MSG-001","sender":"artisan","originalText":"訂金已經收到，多謝。兩日內我會發初稿同建議面料。之後安排量身，預計六星期完成主體刺繡。","translatedText":"Deposit received, thank you. Ill send the first sketches and fabric suggestions within two days, then arrange measurements. Expect about six weeks for the main embroidery.","language":"zh","timestamp":"下午 3:48"},{"messageId":"MSG-001-5","threadId":"MSG-001","sender":"customer","originalText":"Perfect, Ill send my measurements tonight so we stay on track.","translatedText":"太好了，我今晚會傳量身數據，保持進度。","language":"en","timestamp":"下午 4:05"}]}'

echo ""
echo "Uploading CHAT MESSAGES (second batch)..."
npx convex run insertData:insertData '{"table": "chatMessages", "data": [{"messageId":"MSG-002-1","threadId":"MSG-002","sender":"customer","originalText":"Hi! Im based in Sydney and interested in the xiapei cape ensemble. Do you work with remote clients often?","translatedText":"你好！我喺悉尼，好鍾意霞帔披肩長衫套裝。你哋習慣和海外客人合作嗎？","language":"en","timestamp":"上午 9:15"},{"messageId":"MSG-002-2","threadId":"MSG-002","sender":"artisan","originalText":"有架，我哋會先網上量度，再寄出布樣。同時可以用視像會議講解披肩配搭。","translatedText":"Yes, we do. Well guide you through measurements online, mail fabric swatches, and go over cape styling on a video call.","language":"zh","timestamp":"上午 9:28"},{"messageId":"MSG-002-3","threadId":"MSG-002","sender":"customer","originalText":"Thats wonderful. Ill confirm the flight dates and book the fitting slot.","translatedText":"太好了。我會確認航班日子，再預約量身時間。","language":"en","timestamp":"上午 10:40"},{"messageId":"MSG-003-1","threadId":"MSG-003","sender":"customer","originalText":"想整一套母女裝長衫，底色想要碎花但唔想太密。你有咩建議？","translatedText":"Id like a mother-daughter cheongsam set with a floral base thats not too busy. Any suggestions?","language":"zh","timestamp":"昨天"},{"messageId":"MSG-003-2","threadId":"MSG-003","sender":"artisan","originalText":"可以用竹節絲混少少棉，底色做暖奶油色，上面點啲碎花。感覺柔和又易襯。","translatedText":"We can use bamboo silk blended with a little cotton, keep the base a warm cream tone, and scatter delicate florals—soft, versatile, and photo-friendly.","language":"zh","timestamp":"昨天"},{"messageId":"MSG-003-3","threadId":"MSG-003","sender":"customer","originalText":"好啊！今晚前會畫個草圖俾你。","translatedText":"Great! Ill sketch a proposal for you tonight.","language":"zh","timestamp":"昨天"}]}'

echo ""
echo "Messages upload completed!"
